FROM python:3

MAINTAINER Chris W Mann

ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/
COPY /app/ /usr/src/
COPY /shared/ /root/


# Make sure we're running bash
RUN ln -sf /bin/bash /bin/sh

RUN pip install -r app-requirements.txt && chmod +x /usr/src/entrypoint.sh

# RUN useradd -ms /bin/bash appuser
# RUN chown -R appuser *
# RUN usermod -aG sudo appuser
# USER appuser

WORKDIR /usr/src/app