version: '3'

services:
  app:
    restart: always
    image: django_app_dev
    build:
      context: .
      dockerfile: dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    expose:
      - "8000"
    volumes:
      - ../volume/app-django:/usr/src/app/chriswmann
      - ../volume/app-static:/usr/src/app/chriswmann/static
    entrypoint: /usr/src/entrypoint.sh
    env_file: .env

  nginx:
    restart: always
    build:
      context: .
      dockerfile: dockerfile-nginx
    volumes:
        - ../volume/app-static:/www/static
    ports:
        - "80:80"
    depends_on:
      - app

  postgres:
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    env_file: .env

  redis:
    # restart: always
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../volume/redisdata:/data

volumes:
  app-django:
  app-static:
  pgdata:
  redisdata: