FROM python:3

MAINTAINER Chris W Mann

ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/
COPY /analysis/ /usr/src/
COPY /shared/ /root/

# Make sure we're running bash
RUN ln -sf /bin/bash /bin/sh

RUN pip install -r analysis-requirements.txt
CMD /bin/bash

# RUN useradd -ms /bin/bash appuser
# RUN chown -R appuser *
# RUN usermod -aG sudo appuser
# USER appuser