FROM python:3

MAINTAINER Chris W Mann

ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/model
COPY /model/model-requirements.txt /usr/src/model

RUN pip install -r model-requirements.txt

RUN ln -sf /bin/bash /bin/sh
RUN useradd -ms /bin/bash modeluser
USER modeluser