FROM python:3

MAINTAINER Chris W Mann

ENV PYTHONUNBUFFERED 1
WORKDIR /usr/src/
COPY /app/ /usr/src/
COPY /shared/ /root/


# Make sure we're running bash
RUN ln -sf /bin/bash /bin/sh

RUN pip install -r app-requirements.txt

RUN adduser --disabled-password --gecos '' webdev
RUN adduser webdev sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY /shared/ /home/webdev/
USER webdev
RUN source /home/webdev/.bashrc
WORKDIR /usr/src/app
CMD /bin/bash